### ISSUE TITLE
GetObjectAs<T> throwing ArgumentException for multiple data types

### ISSUE THREAD

**Issue by r4reejh** [vicara-hq/kai-dotnet#4]
Encountered problems with types:
- string
- Int32

modifying code from:
```csharp
var type = input.GetObjectAs<string>(Constants.Type);
```
to
```csharp
var type = input[Constants.Type].ToObject<string>();
```
eliminates the error.

Error encountered when Parsing incoming data:
```
|Error|WebSocket.messagec|System.ArgumentException: Can not convert Object to String.
                               at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
                               at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
                               at Newtonsoft.Json.Linq.JToken.ToObject[T]()
                               at Kai.Module.JObjectUtils.GetObjectAs[T](JObject jObject, String key, Boolean& success, T defaultValue, JTokenType unknownType)
                               at Kai.Module.JObjectUtils.GetObjectAs[T](JObject jObject, String key, T defaultValue, JTokenType unknownType)
                               at Kai.Module.KaiListener.ParseIncomingData(JObject input)
                               at Kai.Module.KaiListener.Handle(String data)
                               at Kai.Module.KaiListener.OnWebSocketMessage(Object sender, MessageEventArgs e)
                               at WebSocketSharp.Ext.Emit[TEventArgs](EventHandler`1 eventHandler, Object sender, TEventArgs e)
```

**Comment by rakshith-ravi** [comment]
I've just pushed a fix. Could you test this and let me know if it works? I'll test properly once I'm done with the SDK. Once the SDK gets done, we'll have a lot more freedom to work with these things. We're kinda crippled without the SDK right now. I'll get that done ASAP.

**Comment by r4reejh** [comment]
still throwing error

```
|Error|WebSocket.messagec|System.ArgumentException: Can not convert Object to String.
                             at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
                             at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
                             at Newtonsoft.Json.Linq.JToken.ToObject[T]()
                             at Kai.Module.KaiListener.Handle(String data)
                             at WebSocketSharp.Ext.Emit[TEventArgs](EventHandler`1 eventHandler, Object sender, TEventArgs
e)
                             at WebSocketSharp.WebSocket.messagec(MessageEventArgs e)
```

**Comment by rakshith-ravi** [comment]
Is there an example Json that I can use to reproduce this?

**Comment by r4reejh** [comment]
I got it for this
`{"type":"authenticate", "success":true, "authenticated":true}`

**Comment by rakshith-ravi** [comment]
Reverted back to `ToObject<T>()` under a try/catch. It's less verbose, doesn't explain a lot, but will do for now until that function is implemented properly
